// List based on https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
// but modified

const profanities = [
  /\b2g1c\b/,
  /\b2 girls 1 cup\b/,
  /\bacrotomophilia\b/,
  /\balabama hot pocket\b/,
  /\balaskan pipeline\b/,
  /\banal\b/,
  /\banilingus\b/,
  /\banus\b/,
  /\bapeshit\b/,
  /\barsehole\b/,
  /\bass\b/,
  /\basshole\b/,
  /\bassmunch\b/,
  /\bauto erotic\b/,
  /\bautoerotic\b/,
  /\bbabeland\b/,
  /\bbaby batter\b/,
  /\bbaby juice\b/,
  /\bballs\b/,
  /\bball gag\b/,
  /\bball gravy\b/,
  /\bball kicking\b/,
  /\bball licking\b/,
  /\bball sack\b/,
  /\bball sucking\b/,
  /\bbangbros\b/,
  /\bbangbus\b/,
  /\bbareback\b/,
  /\bbarely legal\b/,
  /\bbarenaked\b/,
  /\bbastard\b/,
  /\bbastardo\b/,
  /\bbastinado\b/,
  /\bbbw\b/,
  /\bbdsm\b/,
  /\bbeaner\b/,
  /\bbeaners\b/,
  /\bbeaver cleaver\b/,
  /\bbeaver lips\b/,
  /\bbeastiality\b/,
  /\bbestiality\b/,
  /\bbig black\b/,
  /\bbig breasts\b/,
  /\bbig knockers\b/,
  /\bbig tits\b/,
  /\bbimbos\b/,
  /\bbirdlock\b/,
  /\bbitch\b/,
  /\bbitches\b/,
  /\bblack cock\b/,
  /\bblonde action\b/,
  /\bblonde on blonde action\b/,
  /\bblowjob\b/,
  /\bblow job\b/,
  /\bblow your load\b/,
  /\bblue waffle\b/,
  /\bblumpkin\b/,
  /\bbollocks\b/,
  /\bbondage\b/,
  /\bboner\b/,
  /\bboob\b/,
  /\bboobs\b/,
  /\bbooty call\b/,
  /\bbrown showers\b/,
  /\bbrunette action\b/,
  /\bbukkake\b/,
  /\bbulldyke\b/,
  /\bbullet vibe\b/,
  /\bbullshit\b/,
  /\bbung hole\b/,
  /\bbunghole\b/,
  /\bbusty\b/,
  /\bbutt\b/,
  /\bbuttcheeks\b/,
  /\bbutthole\b/,
  /\bcamel toe\b/,
  /\bcamgirl\b/,
  /\bcamslut\b/,
  /\bcamwhore\b/,
  /\bcarpet muncher\b/,
  /\bcarpetmuncher\b/,
  /\bchocolate rosebuds\b/,
  /\bcialis\b/,
  /\bcirclejerk\b/,
  /\bcleveland steamer\b/,
  /\bclit\b/,
  /\bclitoris\b/,
  /\bclover clamps\b/,
  /\bclusterfuck\b/,
  /\bcock\b/,
  /\bcocks\b/,
  /\bcoprolagnia\b/,
  /\bcoprophilia\b/,
  /\bcornhole\b/,
  /\bcoon\b/,
  /\bcoons\b/,
  /\bcreampie\b/,
  /\bcum\b/,
  /\bcumming\b/,
  /\bcumshot\b/,
  /\bcumshots\b/,
  /\bcunnilingus\b/,
  /\bcunt\b/,
  /\bdarkie\b/,
  /\bdate rape\b/,
  /\bdaterape\b/,
  /\bdeep throat\b/,
  /\bdeepthroat\b/,
  /\bdendrophilia\b/,
  /\bdick\b/,
  /\bdildo\b/,
  /\bdildos\b/,
  /\bdingleberry\b/,
  /\bdingleberries\b/,
  /\bdirty pillows\b/,
  /\bdirty sanchez\b/,
  /\bdoggie style\b/,
  /\bdoggiestyle\b/,
  /\bdoggy style\b/,
  /\bdoggystyle\b/,
  /\bdog style\b/,
  /\bdolcett\b/,
  /\bdomination\b/,
  /\bdominatrix\b/,
  /\bdommes\b/,
  /\bdonkey punch\b/,
  /\bdouble dong\b/,
  /\bdouble penetration\b/,
  /\bdp action\b/,
  /\bdry hump\b/,
  /\bdvda\b/,
  /\beat my ass\b/,
  /\becchi\b/,
  /\bejaculation\b/,
  /\berotic\b/,
  /\berotism\b/,
  /\bescort\b/,
  /\beunuch\b/,
  /\bfag\b/,
  /\bfaggot\b/,
  /\bfecal\b/,
  /\bfelch\b/,
  /\bfellatio\b/,
  /\bfeltch\b/,
  /\bfemale squirting\b/,
  /\bfemdom\b/,
  /\bfigging\b/,
  /\bfingerbang\b/,
  /\bfingering\b/,
  /\bfisting\b/,
  /\bfoot fetish\b/,
  /\bfootjob\b/,
  /\bfrotting\b/,
  /fuck/,
  //   /\bfuck buttons\b/,
  //   /\bfuckin\b/,
  //   /\bfucking\b/,
  //   /\bfucktards\b/,
  /\bfudge packer\b/,
  /\bfudgepacker\b/,
  /\bfutanari\b/,
  /\bgangbang\b/,
  /\bgang bang\b/,
  /\bgay sex\b/,
  /\bgenitals\b/,
  /\bgiant cock\b/,
  /\bgirl on\b/,
  /\bgirl on top\b/,
  /\bgirls gone wild\b/,
  /\bgoatcx\b/,
  /\bgoatse\b/,
  /\bgod damn\b/,
  /\bgokkun\b/,
  /\bgolden shower\b/,
  /\bgoodpoop\b/,
  /\bgoo girl\b/,
  /\bgoregasm\b/,
  /\bgrope\b/,
  /\bgroup sex\b/,
  /\bg-spot\b/,
  /\bguro\b/,
  /\bhand job\b/,
  /\bhandjob\b/,
  /\bhard core\b/,
  //   /\bhardcore\b/,
  /\bhentai\b/,
  /\bhomoerotic\b/,
  /\bhonkey\b/,
  /\bhooker\b/,
  /\bhorny\b/,
  /\bhot carl\b/,
  /\bhot chick\b/,
  /\bhow to kill\b/,
  /\bhow to murder\b/,
  /\bhuge fat\b/,
  /\bhumping\b/,
  /\bincest\b/,
  /\bintercourse\b/,
  /\bjack off\b/,
  /\bjail bait\b/,
  /\bjailbait\b/,
  /\bjelly donut\b/,
  /\bjerk off\b/,
  /\bjigaboo\b/,
  /\bjiggaboo\b/,
  /\bjiggerboo\b/,
  /\bjizz\b/,
  /\bjuggs\b/,
  /\bkike\b/,
  /\bkinbaku\b/,
  /\bkinkster\b/,
  /\bkinky\b/,
  /\bknobbing\b/,
  /\bleather restraint\b/,
  /\bleather straight jacket\b/,
  /\blemon party\b/,
  /\blivesex\b/,
  /\blolita\b/,
  /\blovemaking\b/,
  /\bmake me come\b/,
  /\bmale squirting\b/,
  /\bmasturbate\b/,
  /\bmasturbating\b/,
  /\bmasturbation\b/,
  /\bmenage a trois\b/,
  /\bmilf\b/,
  /\bmissionary position\b/,
  /\bmong\b/,
  /\bmotherfucker\b/,
  /\bmound of venus\b/,
  /\bmr hands\b/,
  /\bmuff diver\b/,
  /\bmuffdiving\b/,
  /\bnambla\b/,
  /\bnawashi\b/,
  /\bnegro\b/,
  /\bneonazi\b/,
  /\bnigga\b/,
  /\bnigger\b/,
  /\bnig nog\b/,
  /\bnimphomania\b/,
  /\bnipple\b/,
  /\bnipples\b/,
  /\bnsfw\b/,
  /\bnsfw images\b/,
  /\bnude\b/,
  /\bnudity\b/,
  /\bnutten\b/,
  /\bnympho\b/,
  /\bnymphomania\b/,
  /\boctopussy\b/,
  /\bomorashi\b/,
  /\bone cup two girls\b/,
  /\bone guy one jar\b/,
  /\borgasm\b/,
  /\borgy\b/,
  /\bpaedophile\b/,
  /\bpaki\b/,
  /\bpanties\b/,
  /\bpanty\b/,
  /\bpedobear\b/,
  /\bpedophile\b/,
  /\bpeehole\b/,
  /\bpegging\b/,
  /\bpenis\b/,
  /\bphone sex\b/,
  /\bpiece of shit\b/,
  /\bpikey\b/,
  /\bpissing\b/,
  /\bpiss pig\b/,
  /\bpisspig\b/,
  /\bplayboy\b/,
  /\bpleasure chest\b/,
  /\bpole smoker\b/,
  /\bponyplay\b/,
  /\bpoof\b/,
  /\bpoon\b/,
  /\bpoontang\b/,
  /\bpunany\b/,
  /\bpoop chute\b/,
  /\bpoopchute\b/,
  /\bporn\b/,
  /\bporno\b/,
  /\bpornography\b/,
  /\bprince albert piercing\b/,
  /\bpthc\b/,
  /\bpubes\b/,
  /\bpussy\b/,
  /\bqueaf\b/,
  /\bqueef\b/,
  /\bquim\b/,
  /\braghead\b/,
  /\braging boner\b/,
  /\brape\b/,
  /\braping\b/,
  /\brapist\b/,
  /\brectum\b/,
  /\breverse cowgirl\b/,
  /\brimjob\b/,
  /\brimming\b/,
  /\brosy palm\b/,
  /\brosy palm and her 5 sisters\b/,
  /\brusty trombone\b/,
  /\bsadism\b/,
  /\bsantorum\b/,
  /\bscat\b/,
  /\bschlong\b/,
  /\bscissoring\b/,
  /\bscrotum\b/,
  /\bsemen\b/,
  /\bsex\b/,
  /\bsexcam\b/,
  /\bsexo\b/,
  /\bsexy\b/,
  /\bsexual\b/,
  /\bsexually\b/,
  /\bsexuality\b/,
  /\bshaved beaver\b/,
  /\bshaved pussy\b/,
  /\bshemale\b/,
  /\bshibari\b/,
  /\bshit\b/,
  /\bshitblimp\b/,
  /\bshitty\b/,
  /\bshota\b/,
  /\bshrimping\b/,
  /\bskeet\b/,
  /\bslanteye\b/,
  /\bslut\b/,
  /\bs&m\b/,
  /\bsmut\b/,
  /\bsnatch\b/,
  /\bsnowballing\b/,
  /\bsodomize\b/,
  /\bsodomy\b/,
  /\bspastic\b/,
  /\bspic\b/,
  /\bsplooge\b/,
  /\bsplooge moose\b/,
  /\bspooge\b/,
  /\bspread legs\b/,
  /\bspunk\b/,
  /\bstrap on\b/,
  /\bstrapon\b/,
  /\bstrappado\b/,
  /\bstrip club\b/,
  /\bstyle doggy\b/,
  /\bsuck\b/,
  /\bsucks\b/,
  /\bsuicide girls\b/,
  /\bsultry women\b/,
  /\bswastika\b/,
  /\bswinger\b/,
  /\btainted love\b/,
  /\btaste my\b/,
  /\btea bagging\b/,
  /\bthreesome\b/,
  /\bthroating\b/,
  /\bthumbzilla\b/,
  /\btied up\b/,
  /\btight white\b/,
  /\btit\b/,
  /\btits\b/,
  /\btitties\b/,
  /\btitty\b/,
  /\btongue in a\b/,
  /\btopless\b/,
  /\btosser\b/,
  /\btowelhead\b/,
  /\btranny\b/,
  /\btribadism\b/,
  /\btub girl\b/,
  /\btubgirl\b/,
  /\btushy\b/,
  /\btwat\b/,
  /\btwink\b/,
  /\btwinkie\b/,
  /\btwo girls one cup\b/,
  /\bundressing\b/,
  /\bupskirt\b/,
  /\burethra play\b/,
  /\burophilia\b/,
  /\bvagina\b/,
  /\bvenus mound\b/,
  /\bviagra\b/,
  /\bvibrator\b/,
  /\bviolet wand\b/,
  /\bvorarephilia\b/,
  /\bvoyeur\b/,
  /\bvoyeurweb\b/,
  /\bvoyuer\b/,
  /\bvulva\b/,
  /\bwank\b/,
  /\bwanker\b/,
  /\bwankers\b/,
  /\bwetback\b/,
  /\bwet dream\b/,
  /\bwhite power\b/,
  /\bwhore\b/,
  /\bworldsex\b/,
  /\bwrapping men\b/,
  /\bwrinkled starfish\b/,
  /\bxx\b/,
  /\bxxx\b/,
  /\byaoi\b/,
  /\byellow showers\b/,
  /\byiffy\b/,
  /\bzoophilia\b/,
];

export const isProfane = (stringToCheck: string) => {
  return profanities.some((regex) => regex.test(stringToCheck));
};
